method: grid
sweep_anew: Yes
sweep_id: 
metric: 
  name: val_acc
  goal: maximize
parameters:
  num_blocks: 
    values: [1,2,3,4,5]
  in_features: 
    values: [16,32,64,128,256]
  out_features: 
    values: [16,32,64,128,256]
